#!/bin/bash

pushd $( pwd ) > /dev/null

if [ "$#" -ne 1 ]; then
    echo "Please provide jar archive of twsapi as argument."
fi

TMP_DIR=$( mktemp -d )

if [[ ! "$TMP_DIR" || ! -d "$TMP_DIR" ]]; then
    echo "Could not create temporary directory."
    exit 1
fi

echo "Created temporary working directory $TMP_DIR"

function cleanup {
    rm -rf "$TMP_DIR"
    echo "Deleted temporary working directory."
    popd > /dev/null
}

trap cleanup EXIT

echo "Extracting zip archive..."
unzip -q $1 -d $TMP_DIR

VERSION=$( echo $1 | sed 's/.*\.\([0-9]\)\([0-9][0-9]\)\.\([0-9][0-9]\)\.jar/\1.\2.\3/' )

pushd $( pwd ) > /dev/null
cd $TMP_DIR/IBJts/source/JavaClient
mkdir bin
javac -d bin -sourcepath . com/ib/*/*.java
ant
popd > /dev/null

echo "Installing twsapi $VERSION..."
lein localrepo install $TMP_DIR/IBJts/javaclient.jar twsapi $VERSION
