(ns ib-re-actor-976-plus.generated-mappings
  "AUTO-GENERATED mapping declarations from IB Java classes.

  DO NOT EDIT THIS FILE MANUALLY!

  This file is generated by ib-re-actor-976-plus.mapping-generator.
  To regenerate, run: (require 'ib-re-actor-976-plus.mapping-generator)
                      (ib-re-actor-976-plus.mapping-generator/write-generated-mappings!)

  Generated on: 2026-01-03T09:20:02.662247Z

  Usage:
    (require '[ib-re-actor-976-plus.mapping-auto :refer [->map map->]])
    (require '[ib-re-actor-976-plus.generated-mappings])  ; Loads implementations

    (->map java-object)              ; Java → Clojure map
    (map-> Class clojure-map)        ; Clojure map → Java
  "
  (:require
    [ib-re-actor-976-plus.mapping-auto :refer [defmapping defmapping-readonly]]))

(defmapping com.ib.client.ComboLeg
            [:conid conid]
            [:ratio ratio]
            [:action action :translation :order-action]
            [:exchange exchange]
            [:open-close openClose]
            [:short-sale-slot shortSaleSlot]
            [:designated-location designatedLocation]
            [:exempt-code exemptCode])


(defmapping com.ib.client.CommissionAndFeesReport
            [:exec-id execId]
            [:commission-and-fees commissionAndFees]
            [:currency currency]
            [:realized-pnl realizedPNL]
            [:yield yield]
            [:yield-redemption-date yieldRedemptionDate])


(defmapping com.ib.client.Contract
            [:conid conid]
            [:symbol symbol]
            [:sec-type secType :translation :security-type]
            [:last-trade-date-or-contract-month lastTradeDateOrContractMonth]
            [:last-trade-date lastTradeDate]
            [:strike strike]
            [:right right :translation :right]
            [:multiplier multiplier :translation :double-string]
            [:exchange exchange]
            [:primary-exch primaryExch]
            [:currency currency]
            [:local-symbol localSymbol]
            [:trading-class tradingClass]
            [:sec-id-type secIdType :translation :security-id-type]
            [:sec-id secId]
            [:description description]
            [:issuer-id issuerId]
            [:delta-neutral-contract deltaNeutralContract]
            [:include-expired includeExpired]
            [:combo-legs-descrip comboLegsDescrip]
            [:combo-legs comboLegs])


(defmapping-readonly com.ib.client.ContractCondition
            [:con-id conId]
            [:exchange exchange])


(defmapping com.ib.client.ContractDescription
            [:contract contract]
            [:derivative-sec-types derivativeSecTypes])


(defmapping com.ib.client.ContractDetails
            [:contract contract]
            [:market-name marketName]
            [:min-tick minTick]
            [:price-magnifier priceMagnifier]
            [:order-types orderTypes :translation :order-types]
            [:valid-exchanges validExchanges :translation :exchanges]
            [:under-conid underConid]
            [:long-name longName]
            [:contract-month contractMonth]
            [:industry industry]
            [:category category]
            [:subcategory subcategory]
            [:time-zone-id timeZoneId]
            [:trading-hours tradingHours]
            [:liquid-hours liquidHours]
            [:ev-rule evRule]
            [:ev-multiplier evMultiplier]
            [:sec-id-list secIdList]
            [:agg-group aggGroup]
            [:under-symbol underSymbol]
            [:under-sec-type underSecType]
            [:market-rule-ids marketRuleIds]
            [:real-expiration-date realExpirationDate]
            [:last-trade-time lastTradeTime]
            [:stock-type stockType]
            [:min-size minSize :translation :string-to-decimal]
            [:size-increment sizeIncrement :translation :string-to-decimal]
            [:suggested-size-increment suggestedSizeIncrement :translation :string-to-decimal]
            [:min-algo-size minAlgoSize :translation :string-to-decimal]
            [:cusip cusip]
            [:ratings ratings]
            [:desc-append descAppend]
            [:bond-type bondType]
            [:coupon-type couponType]
            [:callable callable]
            [:putable putable]
            [:coupon coupon]
            [:convertible convertible]
            [:maturity maturity]
            [:issue-date issueDate]
            [:next-option-date nextOptionDate]
            [:next-option-type nextOptionType]
            [:next-option-partial nextOptionPartial]
            [:notes notes]
            [:fund-name fundName]
            [:fund-family fundFamily]
            [:fund-type fundType]
            [:fund-front-load fundFrontLoad]
            [:fund-back-load fundBackLoad]
            [:fund-back-load-time-interval fundBackLoadTimeInterval]
            [:fund-management-fee fundManagementFee]
            [:fund-closed fundClosed]
            [:fund-closed-for-new-investors fundClosedForNewInvestors]
            [:fund-closed-for-new-money fundClosedForNewMoney]
            [:fund-notify-amount fundNotifyAmount]
            [:fund-minimum-initial-purchase fundMinimumInitialPurchase]
            [:fund-subsequent-minimum-purchase fundSubsequentMinimumPurchase]
            [:fund-blue-sky-states fundBlueSkyStates]
            [:fund-blue-sky-territories fundBlueSkyTerritories]
            [:fund-distribution-policy-indicator fundDistributionPolicyIndicator]
            [:fund-asset-type fundAssetType]
            [:ineligibility-reason-list ineligibilityReasonList]
            [:event-contract1 eventContract1]
            [:event-contract-description1 eventContractDescription1]
            [:event-contract-description2 eventContractDescription2])


(defmapping com.ib.client.DeltaNeutralContract
            [:conid conid]
            [:delta delta]
            [:price price])


(defmapping com.ib.client.DepthMktDataDescription
            [:exchange exchange]
            [:sec-type secType]
            [:listing-exch listingExch]
            [:service-data-type serviceDataType]
            [:agg-group aggGroup])


(defmapping-readonly com.ib.client.EClient
            [:optional-capabilities optionalCapabilities])


(defmapping com.ib.client.Execution
            [:order-id orderId]
            [:client-id clientId]
            [:exec-id execId]
            [:time time]
            [:acct-number acctNumber]
            [:exchange exchange]
            [:side side]
            [:shares shares :translation :string-to-decimal]
            [:price price]
            [:perm-id permId]
            [:liquidation liquidation]
            [:cum-qty cumQty :translation :string-to-decimal]
            [:avg-price avgPrice]
            [:order-ref orderRef]
            [:ev-rule evRule]
            [:ev-multiplier evMultiplier]
            [:model-code modelCode]
            [:last-liquidity lastLiquidity]
            [:pending-price-revision pendingPriceRevision]
            [:submitter submitter]
            [:opt-exercise-or-lapse-type optExerciseOrLapseType])


(defmapping-readonly com.ib.client.ExecutionCondition
            [:exchange exchange]
            [:sec-type secType]
            [:symbol symbol])


(defmapping com.ib.client.ExecutionFilter
            [:client-id clientId]
            [:acct-code acctCode]
            [:time time]
            [:symbol symbol]
            [:sec-type secType]
            [:exchange exchange]
            [:side side]
            [:last-n-days lastNDays]
            [:specific-dates specificDates])


(defmapping com.ib.client.FamilyCode
            [:account-id accountID]
            [:family-code-str familyCodeStr])


(defmapping-readonly com.ib.client.HistogramEntry
            [:price price]
            [:size size :translation :string-to-decimal])


(defmapping com.ib.client.IneligibilityReason
            [:id id]
            [:description description])


(defmapping-readonly com.ib.client.MarginCondition
            [:percent percent])


(defmapping com.ib.client.NewsProvider
            [:provider-code providerCode]
            [:provider-name providerName])


(defmapping-readonly com.ib.client.OperatorCondition
            [:is-more isMore])


(defmapping com.ib.client.Order
            [:client-id clientId]
            [:order-id orderId]
            [:perm-id permId]
            [:parent-id parentId]
            [:action action :translation :order-action]
            [:total-quantity totalQuantity :translation :string-to-decimal]
            [:display-size displaySize]
            [:order-type orderType :translation :order-type]
            [:lmt-price lmtPrice]
            [:aux-price auxPrice]
            [:tif tif :translation :time-in-force]
            [:account account]
            [:settling-firm settlingFirm]
            [:clearing-account clearingAccount]
            [:clearing-intent clearingIntent]
            [:all-or-none allOrNone]
            [:block-order blockOrder]
            [:hidden hidden]
            [:outside-rth outsideRth]
            [:sweep-to-fill sweepToFill]
            [:percent-offset percentOffset]
            [:trailing-percent trailingPercent]
            [:trail-stop-price trailStopPrice]
            [:min-qty minQty]
            [:good-after-time goodAfterTime]
            [:good-till-date goodTillDate]
            [:oca-group ocaGroup]
            [:order-ref orderRef]
            [:rule80-a rule80A]
            [:oca-type ocaType]
            [:trigger-method triggerMethod]
            [:active-start-time activeStartTime]
            [:active-stop-time activeStopTime]
            [:fa-group faGroup]
            [:fa-method faMethod]
            [:fa-percentage faPercentage]
            [:volatility volatility]
            [:volatility-type volatilityType]
            [:continuous-update continuousUpdate]
            [:reference-price-type referencePriceType]
            [:delta-neutral-order-type deltaNeutralOrderType :translation :order-type]
            [:delta-neutral-aux-price deltaNeutralAuxPrice]
            [:delta-neutral-con-id deltaNeutralConId]
            [:delta-neutral-open-close deltaNeutralOpenClose]
            [:delta-neutral-short-sale deltaNeutralShortSale]
            [:delta-neutral-short-sale-slot deltaNeutralShortSaleSlot]
            [:delta-neutral-designated-location deltaNeutralDesignatedLocation]
            [:scale-init-level-size scaleInitLevelSize]
            [:scale-subs-level-size scaleSubsLevelSize]
            [:scale-price-increment scalePriceIncrement]
            [:scale-price-adjust-value scalePriceAdjustValue]
            [:scale-price-adjust-interval scalePriceAdjustInterval]
            [:scale-profit-offset scaleProfitOffset]
            [:scale-auto-reset scaleAutoReset]
            [:scale-init-position scaleInitPosition]
            [:scale-init-fill-qty scaleInitFillQty]
            [:scale-random-percent scaleRandomPercent]
            [:scale-table scaleTable]
            [:hedge-type hedgeType]
            [:hedge-param hedgeParam]
            [:algo-strategy algoStrategy]
            [:algo-params algoParams]
            [:algo-id algoId]
            [:smart-combo-routing-params smartComboRoutingParams]
            [:order-combo-legs orderComboLegs]
            [:what-if whatIf]
            [:transmit transmit]
            [:override-percentage-constraints overridePercentageConstraints]
            [:open-close openClose]
            [:origin origin]
            [:short-sale-slot shortSaleSlot]
            [:designated-location designatedLocation]
            [:exempt-code exemptCode]
            [:delta-neutral-settling-firm deltaNeutralSettlingFirm]
            [:delta-neutral-clearing-account deltaNeutralClearingAccount]
            [:delta-neutral-clearing-intent deltaNeutralClearingIntent]
            [:discretionary-amt discretionaryAmt]
            [:opt-out-smart-routing optOutSmartRouting]
            [:auction-strategy auctionStrategy]
            [:starting-price startingPrice]
            [:stock-ref-price stockRefPrice]
            [:delta delta]
            [:stock-range-lower stockRangeLower]
            [:stock-range-upper stockRangeUpper]
            [:basis-points basisPoints]
            [:basis-points-type basisPointsType]
            [:not-held notHeld]
            [:order-misc-options orderMiscOptions]
            [:solicited solicited]
            [:randomize-size randomizeSize]
            [:randomize-price randomizePrice]
            [:reference-contract-id referenceContractId]
            [:pegged-change-amount peggedChangeAmount]
            [:is-pegged-change-amount-decrease isPeggedChangeAmountDecrease]
            [:reference-change-amount referenceChangeAmount]
            [:reference-exchange-id referenceExchangeId]
            [:adjusted-order-type adjustedOrderType :translation :order-type]
            [:trigger-price triggerPrice]
            [:adjusted-stop-price adjustedStopPrice]
            [:adjusted-stop-limit-price adjustedStopLimitPrice]
            [:adjusted-trailing-amount adjustedTrailingAmount]
            [:adjustable-trailing-unit adjustableTrailingUnit]
            [:lmt-price-offset lmtPriceOffset]
            [:conditions conditions]
            [:conditions-cancel-order conditionsCancelOrder]
            [:conditions-ignore-rth conditionsIgnoreRth]
            [:model-code modelCode]
            [:ext-operator extOperator]
            [:soft-dollar-tier softDollarTier]
            [:cash-qty cashQty]
            [:mifid2-decision-maker mifid2DecisionMaker]
            [:mifid2-decision-algo mifid2DecisionAlgo]
            [:mifid2-execution-trader mifid2ExecutionTrader]
            [:mifid2-execution-algo mifid2ExecutionAlgo]
            [:dont-use-auto-price-for-hedge dontUseAutoPriceForHedge]
            [:is-oms-container isOmsContainer]
            [:discretionary-up-to-limit-price discretionaryUpToLimitPrice]
            [:auto-cancel-date autoCancelDate]
            [:filled-quantity filledQuantity :translation :string-to-decimal]
            [:ref-futures-con-id refFuturesConId]
            [:auto-cancel-parent autoCancelParent]
            [:shareholder shareholder]
            [:imbalance-only imbalanceOnly]
            [:route-marketable-to-bbo routeMarketableToBbo]
            [:parent-perm-id parentPermId]
            [:use-price-mgmt-algo usePriceMgmtAlgo]
            [:duration duration]
            [:post-to-ats postToAts]
            [:advanced-error-override advancedErrorOverride]
            [:manual-order-time manualOrderTime]
            [:min-trade-qty minTradeQty]
            [:min-compete-size minCompeteSize]
            [:compete-against-best-offset competeAgainstBestOffset]
            [:mid-offset-at-whole midOffsetAtWhole]
            [:mid-offset-at-half midOffsetAtHalf]
            [:customer-account customerAccount]
            [:professional-customer professionalCustomer]
            [:bond-accrued-interest bondAccruedInterest]
            [:include-overnight includeOvernight]
            [:manual-order-indicator manualOrderIndicator]
            [:submitter submitter]
            [:post-only postOnly]
            [:allow-pre-open allowPreOpen]
            [:ignore-open-auction ignoreOpenAuction]
            [:deactivate deactivate]
            [:seek-price-improvement seekPriceImprovement]
            [:what-if-type whatIfType]
            [:sl-order-id slOrderId]
            [:sl-order-type slOrderType :translation :order-types]
            [:pt-order-id ptOrderId]
            [:pt-order-type ptOrderType :translation :order-types])


(defmapping com.ib.client.OrderAllocation
            [:account account]
            [:position position :translation :string-to-decimal]
            [:position-desired positionDesired :translation :string-to-decimal]
            [:position-after positionAfter :translation :string-to-decimal]
            [:desired-alloc-qty desiredAllocQty :translation :string-to-decimal]
            [:allowed-alloc-qty allowedAllocQty :translation :string-to-decimal]
            [:is-monetary isMonetary])


(defmapping com.ib.client.OrderCancel
            [:manual-order-cancel-time manualOrderCancelTime]
            [:ext-operator extOperator]
            [:manual-order-indicator manualOrderIndicator])


(defmapping com.ib.client.OrderComboLeg
            [:price price])


(defmapping-readonly com.ib.client.OrderState
            [:status status :translation :order-status]
            [:init-margin-before initMarginBefore]
            [:maint-margin-before maintMarginBefore]
            [:equity-with-loan-before equityWithLoanBefore]
            [:init-margin-change initMarginChange]
            [:maint-margin-change maintMarginChange]
            [:equity-with-loan-change equityWithLoanChange]
            [:init-margin-after initMarginAfter]
            [:maint-margin-after maintMarginAfter]
            [:equity-with-loan-after equityWithLoanAfter]
            [:commission-and-fees commissionAndFees]
            [:min-commission-and-fees minCommissionAndFees]
            [:max-commission-and-fees maxCommissionAndFees]
            [:commission-and-fees-currency commissionAndFeesCurrency]
            [:margin-currency marginCurrency]
            [:init-margin-before-outside-rth initMarginBeforeOutsideRTH]
            [:maint-margin-before-outside-rth maintMarginBeforeOutsideRTH]
            [:equity-with-loan-before-outside-rth equityWithLoanBeforeOutsideRTH]
            [:init-margin-change-outside-rth initMarginChangeOutsideRTH]
            [:maint-margin-change-outside-rth maintMarginChangeOutsideRTH]
            [:equity-with-loan-change-outside-rth equityWithLoanChangeOutsideRTH]
            [:init-margin-after-outside-rth initMarginAfterOutsideRTH]
            [:maint-margin-after-outside-rth maintMarginAfterOutsideRTH]
            [:equity-with-loan-after-outside-rth equityWithLoanAfterOutsideRTH]
            [:suggested-size suggestedSize :translation :string-to-decimal]
            [:reject-reason rejectReason]
            [:order-allocations orderAllocations]
            [:warning-text warningText]
            [:completed-time completedTime]
            [:completed-status completedStatus])


(defmapping-readonly com.ib.client.PercentChangeCondition
            [:change-percent changePercent])


(defmapping-readonly com.ib.client.PriceCondition
            [:price price]
            [:trigger-method triggerMethod])


(defmapping com.ib.client.PriceIncrement
            [:low-edge lowEdge]
            [:increment increment])


(defmapping-readonly com.ib.client.ScannerSubscription
            [:number-of-rows numberOfRows]
            [:instrument instrument]
            [:location-code locationCode]
            [:scan-code scanCode]
            [:above-price abovePrice]
            [:below-price belowPrice]
            [:above-volume aboveVolume]
            [:average-option-volume-above averageOptionVolumeAbove]
            [:market-cap-above marketCapAbove]
            [:market-cap-below marketCapBelow]
            [:moody-rating-above moodyRatingAbove]
            [:moody-rating-below moodyRatingBelow]
            [:sp-rating-above spRatingAbove]
            [:sp-rating-below spRatingBelow]
            [:maturity-date-above maturityDateAbove]
            [:maturity-date-below maturityDateBelow]
            [:coupon-rate-above couponRateAbove]
            [:coupon-rate-below couponRateBelow]
            [:exclude-convertible excludeConvertible]
            [:scanner-setting-pairs scannerSettingPairs]
            [:stock-type-filter stockTypeFilter])


(defmapping-readonly com.ib.client.TickAttrib
            [:can-auto-execute canAutoExecute]
            [:past-limit pastLimit]
            [:pre-open preOpen])


(defmapping-readonly com.ib.client.TickAttribBidAsk
            [:bid-past-low bidPastLow]
            [:ask-past-high askPastHigh])


(defmapping-readonly com.ib.client.TickAttribLast
            [:past-limit pastLimit]
            [:unreported unreported])


(defmapping-readonly com.ib.client.TimeCondition
            [:time time])


(defmapping-readonly com.ib.client.VolumeCondition
            [:volume volume])
